//--- CHARTEVENT_KEYDOWN
#define KEY_SWITCH_TRADELINE     49  //#1
#define KEY_SWITCH_TRADE_METHOD  50  //#2
#define KEY_RESET_TRADELINE      51  //#3
#define KEY_SWITCH_RRFIB         70  //#F
#define KEY_SWITCH_PROFITLINE    82  //#R

#define MOUSEMOVE_ACTION_CLICK_DRAG 1
